### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by erpadmin** [andrewbrey/netflix-tweaked#19]
i've installed node.js 
then
npm install gulp-cli -g
npm install gulp -D

```
C:\Users\someuser\Downloads\netflix-tweaked-master>gulp package
[19:46:37] Failed to load external module @babel/register
[19:46:37] Requiring external module babel-register
[19:46:37] Using gulpfile ~\Downloads\netflix-tweaked-master\gulpfile.babel.js
[19:46:37] Starting 'package'...
[19:46:37] Starting 'clean'...
[19:46:37] Finished 'clean' after 3.07 ms
[19:46:37] Starting 'build-chrome'...
[19:46:37] Starting 'lint'...
[19:46:38] Finished 'lint' after 547 ms
[19:46:38] Starting 'babel'...
[19:46:38] Finished 'babel' after 109 ms
[19:46:38] Starting 'chromeManifest'...
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\someuser\Downloads\netflix-tweaked-master\app\styles\netflix-tweak.css'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at DestroyableTransform.<anonymous> (C:\Users\someuser\Downloads\netflix-tweaked-master\node_modules\gulp-chrome-manifest\index.js:114:19)
    at Array.forEach (<anonymous>)
    at DestroyableTransform._transform (C:\Users\someuser\Downloads\netflix-tweaked-master\node_modules\gulp-chrome-manifest\index.js:111:17)
    at DestroyableTransform.Transform._read (C:\Users\someuser\Downloads\netflix-tweaked-master\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\someuser\Downloads\netflix-tweaked-master\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\someuser\Downloads\netflix-tweaked-master\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\someuser\Downloads\netflix-tweaked-master\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\Users\someuser\Downloads\netflix-tweaked-master\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:334:11)
```

**Comment by andrewbrey** [comment]
@erpadmin I do not believe that the latest versions of gulp and the gulp-cli are compatible with the gulp tasks defined for this project. The build pipeline I am using in this repo is based on an older gulp (I want to say v3?) and the latest gulp is, as far as I'm aware, a very different animal.

**Comment by andrewbrey** [comment]
@erpadmin I just had to check and confirm - yes, the `package.json` for this repo calls for gulp `v3.9.1`, and you should use the locally installed binaries, not the global packages for your dev setup if you're going to work on a fix to the issue you submitted earlier.

Cheers!

**Comment by erpadmin** [comment]
i dont see the issue

>gulp -v
[20:15:05] Failed to load external module @babel/register
[20:15:05] Requiring external module babel-register
[20:15:05] CLI version 2.0.1
[20:15:05] Local version 3.9.1

am i'm not understanding locally vs global

**Comment by andrewbrey** [comment]
@erpadmin Yes, I think the issue is that when you run `npm install` from the project directory, you'll get a locally installed version of gulp (in `node_modules/bin`) that is in conflict with the version you just installed with `npm install gulp-cli -g`. I have run into the specific `@babel/register` error before with other packages, and it's not too bad to fix (just Google around), but it will probably be easier for you just to uninstall the globally installed gulp-cli (`npm uninstall gulp-cli -g` I believe), then revert any changes you may have to the package.json, then run `npm install`, then run `npm prune` to ensure that any vestiges of the `gulp-cli` package are removed from the local node_modules directory.
